server:
  port: 8701
spring:
  application:
    name: cnsy-log-register-server
  profiles:
    active: dev1
eureka:
  instance:
    hostname: host0
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://host1:8702/eureka/,http://host2:8703/eureka/
  